site_name: SRE Toolbox Community Catalog
site_description: Community-managed toolkit registry for the Toolbox framework.
repo_url: https://github.com/sre-toolbox-community/ideal-octo-engine
site_dir: site
use_directory_urls: true

nav:
  - Home: index.md
  - Operations:
      - Catalog maintenance: catalog.md
      - Dynamic bundler: bundler.md
  - Guidance:
      - Architecture recap: architecture.md
      - Testing checklist: testing.md
      - Contributor onboarding: onboarding.md
      - Changelog: changelog.md
  - Toolkits:
      - Browse toolkits: toolkit-browser.md
      - Toolkit authoring:
          - Overview: toolkit-authoring/overview.md
          - Backend & worker guide: toolkit-authoring/backend-and-worker.md
          - Frontend integration: toolkit-authoring/frontend.md
          - Testing & release: toolkit-authoring/testing-and-release.md
          - Versioning: toolkit-authoring/versioning.md
          - Author checklist: toolkit-authoring.md
      - Subnet Calculator toolkit:
          - Overview: toolkits/subnet-cheatsheet/index.md
          - Calculator workflows: toolkits/subnet-cheatsheet/calculator.md
          - Prefix cheat sheet reference: toolkits/subnet-cheatsheet/prefix-reference.md
      - Sample Diagnostics Toolkit: toolkits/sample-toolkit/index.md
      
plugins:
  - search
  - macros:
      module_name: macros/main

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
