site_name: SRE Toolbox Community Catalog
site_description: Community-managed toolkit registry for the Toolbox framework.
repo_url: https://github.com/sre-toolbox-community/ideal-octo-engine
site_dir: site
use_directory_urls: true

nav:
  - Home: index.md
  - Operations:
      - Catalog maintenance: catalog.md
      - Dynamic bundler: bundler.md
  - Guidance:
      - Architecture recap: architecture.md
      - Toolkit authoring: toolkit-authoring.md
      - Testing checklist: testing.md
      - Contributor onboarding: onboarding.md
      - Task backlog (TODO.yml): TODO.yml
      - Changelog: changelog.md
  - Toolkits:
      - Regex Toolkit: toolkits/regex/index.md
      - Sample Diagnostics Toolkit: toolkits/sample-toolkit/index.md

plugins:
  - search
  - macros:
      module_name: macros/main

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
