site_name: SRE Toolbox Community Catalog
site_description: Community-managed toolkit registry for the Toolbox framework.
repo_url: https://github.com/sre-toolbox-community/ideal-octo-engine
site_dir: site
use_directory_urls: true

nav:
  - Home: index.md
  - Catalog:
      - Browse toolkits: catalog/browse.md
      - Sample Diagnostics Toolkit: sample-toolkit/index.md
  - Documentation:
      - Repository structure: structure.md
      - Changelog: changelog.md
      - Toolkit authoring:
          - Getting started: toolkit-authoring/getting-started.md
          - Packaging checklist: toolkit-authoring/packaging.md
      - Governance:
          - Contribution process: governance/contribution-process.md
          - Security review: governance/security-review.md
          - Decision log: governance/decision-log.md

plugins:
  - search
  - macros:
      module_name: macros/main

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
