name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Validate repository
        run: |
          scripts/validate-repo.sh
  docs-build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Build documentation
        run: |
          mkdocs build --strict --clean --site-dir site
          mkdir -p site/catalog
          cp -R catalog/. site/catalog/
  package-sample-toolkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package sample toolkit
        run: |
          scripts/package-toolkit.sh sample-toolkit
